//! Non-root Hub and Collector service definitions.
//!
//! Rendering is pure: deployment uploads the returned bytes with restrictive
//! permissions and then asks the platform service manager to restart them.
//! No password, token, or private key is accepted by this module.

use anyhow::{bail, Result};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ServicePlatform {
    Systemd,
    Launchd,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ServiceSpec {
    pub platform: ServicePlatform,
    pub user: String,
    pub uid: u32,
    pub executable: PathBuf,
    pub config_path: PathBuf,
    pub usage_db_path: PathBuf,
    pub collector_db_path: PathBuf,
    pub hub_db_path: PathBuf,
    pub hub_port: u16,
    pub listener: String,
    pub service_dir: PathBuf,
}

impl ServiceSpec {
    pub fn validate(&self) -> Result<()> {
        if self.uid == 0 || self.user.trim().is_empty() || self.user == "root" {
            bail!("Dirtydash services must run as a selected non-root user");
        }
        if self.hub_port == 0 {
            bail!("Hub service port must be non-zero");
        }
        for path in [
            &self.executable,
            &self.config_path,
            &self.usage_db_path,
            &self.collector_db_path,
            &self.hub_db_path,
            &self.service_dir,
        ] {
            validate_path(path)?;
        }
        if !self.listener.chars().all(|character| {
            character.is_ascii_lowercase() || character.is_ascii_digit() || character == '-'
        }) {
            bail!("service listener mode is not a fixed allowlisted value");
        }
        Ok(())
    }

    pub fn render(&self) -> Result<Vec<RenderedService>> {
        self.validate()?;
        match self.platform {
            ServicePlatform::Systemd => Ok(vec![
                RenderedService {
                    path: self.service_dir.join("dirtydash-hub.service"),
                    mode: 0o644,
                    contents: render_systemd_hub(self),
                },
                RenderedService {
                    path: self.service_dir.join("dirtydash-collector.service"),
                    mode: 0o644,
                    contents: render_systemd_collector(self),
                },
            ]),
            ServicePlatform::Launchd => Ok(vec![
                RenderedService {
                    path: self.service_dir.join("dev.dirtydash.hub.plist"),
                    mode: 0o644,
                    contents: render_launchd_hub(self),
                },
                RenderedService {
                    path: self.service_dir.join("dev.dirtydash.collector.plist"),
                    mode: 0o644,
                    contents: render_launchd_collector(self),
                },
            ]),
        }
    }

    pub fn restart_action(&self) -> &'static str {
        match self.platform {
            ServicePlatform::Systemd => "systemctl --user daemon-reload && systemctl --user restart dirtydash-hub.service dirtydash-collector.service",
            ServicePlatform::Launchd => "launchctl kickstart -k gui/$UID/dev.dirtydash.hub && launchctl kickstart -k gui/$UID/dev.dirtydash.collector",
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RenderedService {
    pub path: PathBuf,
    pub mode: u32,
    pub contents: String,
}

fn render_systemd_hub(spec: &ServiceSpec) -> String {
    format!(
        "# Generated by dirtydash; this is a per-user non-root service.\n[Unit]\nDescription=Dirtydash Hub\nAfter=network-online.target\nWants=network-online.target\n\n[Service]\nType=simple\nUser={}\nExecStart={} --config {} --db {} serve --hub --host 127.0.0.1 --port {} --listener {}\nRestart=on-failure\nRestartSec=3\nNoNewPrivileges=yes\nPrivateTmp=yes\n\n[Install]\nWantedBy=default.target\n",
        systemd_escape(&spec.user),
        systemd_escape_path(&spec.executable),
        systemd_escape_path(&spec.config_path),
        systemd_escape_path(&spec.hub_db_path),
        spec.hub_port,
        systemd_escape(&spec.listener),
    )
}

fn render_systemd_collector(spec: &ServiceSpec) -> String {
    format!(
        "# Generated by dirtydash; this is a per-user non-root service.\n[Unit]\nDescription=Dirtydash local Collector\nAfter=network-online.target\nWants=network-online.target\n\n[Service]\nType=simple\nUser={}\nExecStart={} --config {} --db {} collector run\nRestart=on-failure\nRestartSec=3\nNoNewPrivileges=yes\nPrivateTmp=yes\n\n[Install]\nWantedBy=default.target\n",
        systemd_escape(&spec.user),
        systemd_escape_path(&spec.executable),
        systemd_escape_path(&spec.config_path),
        systemd_escape_path(&spec.usage_db_path),
    )
}

fn render_launchd_hub(spec: &ServiceSpec) -> String {
    plist(
        "dev.dirtydash.hub",
        "Dirtydash Hub",
        &[
            spec.executable.clone(),
            PathBuf::from("--config"),
            spec.config_path.clone(),
            PathBuf::from("--db"),
            spec.hub_db_path.clone(),
            PathBuf::from("serve"),
            PathBuf::from("--hub"),
            PathBuf::from("--host"),
            PathBuf::from("127.0.0.1"),
            PathBuf::from("--port"),
            PathBuf::from(spec.hub_port.to_string()),
            PathBuf::from("--listener"),
            PathBuf::from(spec.listener.as_str()),
        ],
        &spec.user,
    )
}

fn render_launchd_collector(spec: &ServiceSpec) -> String {
    plist(
        "dev.dirtydash.collector",
        "Dirtydash local Collector",
        &[
            spec.executable.clone(),
            PathBuf::from("--config"),
            spec.config_path.clone(),
            PathBuf::from("--db"),
            spec.usage_db_path.clone(),
            PathBuf::from("collector"),
            PathBuf::from("run"),
        ],
        &spec.user,
    )
}

fn plist(label: &str, description: &str, args: &[PathBuf], user: &str) -> String {
    let arguments = args
        .iter()
        .map(|argument| {
            format!(
                "        <string>{}</string>\n",
                xml_escape(&argument.display().to_string())
            )
        })
        .collect::<String>();
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n<plist version=\"1.0\">\n<dict>\n    <key>Label</key><string>{}</string>\n    <key>Comment</key><string>{}</string>\n    <key>UserName</key><string>{}</string>\n    <key>ProgramArguments</key>\n    <array>\n{}    </array>\n    <key>RunAtLoad</key><true/>\n    <key>KeepAlive</key><true/>\n    <key>ProcessType</key><string>Interactive</string>\n</dict>\n</plist>\n",
        xml_escape(label),
        xml_escape(description),
        xml_escape(user),
        arguments,
    )
}

fn validate_path(path: &Path) -> Result<()> {
    if path.as_os_str().is_empty()
        || path
            .to_string_lossy()
            .chars()
            .any(|character| character.is_control())
    {
        bail!("service path is empty or contains control characters");
    }
    Ok(())
}

fn systemd_escape(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace(' ', "\\x20")
        .replace('\t', "\\x09")
        .replace('"', "\\\"")
}

fn systemd_escape_path(path: &Path) -> String {
    systemd_escape(&path.display().to_string())
}

fn xml_escape(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&apos;")
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn spec(platform: ServicePlatform) -> ServiceSpec {
        let dir = tempdir().unwrap().keep();
        ServiceSpec {
            platform,
            user: "delta".to_string(),
            uid: 1000,
            executable: dir.join("current/dirtydash"),
            config_path: dir.join("config/config.toml"),
            usage_db_path: dir.join("data/usage.sqlite3"),
            collector_db_path: dir.join("data/collector.sqlite3"),
            hub_db_path: dir.join("data/hub.sqlite3"),
            hub_port: 4599,
            listener: "tailscale".to_string(),
            service_dir: dir.join("services"),
        }
    }

    #[test]
    fn systemd_services_are_explicitly_non_root_and_restartable() {
        let services = spec(ServicePlatform::Systemd).render().unwrap();
        assert_eq!(services.len(), 2);
        assert!(services[0].contents.contains("User=delta"));
        assert!(services[0].contents.contains("NoNewPrivileges=yes"));
        assert!(services[0].contents.contains("serve --hub"));
        assert!(services[1].contents.contains("collector run"));
    }

    #[test]
    fn launchd_agents_have_user_and_separate_hub_collector_labels() {
        let services = spec(ServicePlatform::Launchd).render().unwrap();
        assert!(services[0].contents.contains("dev.dirtydash.hub"));
        assert!(services[0]
            .contents
            .contains("<key>UserName</key><string>delta</string>"));
        assert!(services[1].contents.contains("dev.dirtydash.collector"));
    }

    #[test]
    fn root_service_is_rejected() {
        let mut service = spec(ServicePlatform::Systemd);
        service.uid = 0;
        assert!(service.render().is_err());
    }
}
